Repository bcgov/devhub-app-web, pull requests merged in 2018-12, with the labels that each got.

#161 updated the fronts of the cards
  app-web/src/components/Cards/Card/Card.module.css
  app-web/src/hoc/Card.js
Labels: In Prod

#166 updated the table headers so they don't break a word before its compl…
  app-web/src/templates/SourceMarkdown.module.css
Labels: bug, good first issue

#167 Filter Navigation Changed from Select List to a Nav Bar
  app-web/__tests__/components/__snapshots__/Layout.test.js.snap
  app-web/__tests__/components/__snapshots__/PrimaryFilter.test.js.snap
  app-web/__tests__/components/__snapshots__/PrimaryHeader.test.js.snap
  app-web/src/components/PrimaryFilter/PrimaryFilter.js
  app-web/src/components/PrimaryFilter/PrimaryFilter.module.css
  app-web/src/components/PrimaryHeader/PrimaryHeader.js
  app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
  app-web/src/components/UI/Banner/Banner.module.css
  app-web/src/components/UI/Button/Button.module.css
  app-web/src/pages/index.js
  app-web/src/store/reducers/ui.js
Labels: enhancement, refactor

#172 Fix hamburger visible on large screen issue
  app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
Labels: bug

#171 fixed footer to remain on the bottom despite the length of the page c…
  app-web/src/components/PrimaryFooter/PrimaryFooter.module.css
  app-web/src/pages/index.module.css
Labels: enhancement, good first issue

#174 Siphon Can take collections (a source composed of multiple sources)
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/constants.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSource.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/plugins/gatsby-source-github-all/utils/transformer.js
  app-web/source-registry/registry.yml
Labels: enhancement, technical debt

#176 Docs/siphon collections
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
  docs/images/story.png
  docs/registerRepo.md
  docs/siphon.md
  docs/sourceCollections.md
Labels: documentation, technical debt

#183 Update Siphon Docs for sourcing file/files in registry
  docs/registerRepo.md
  docs/registry.sample.yml
Labels: documentation

#184 Add more examples on how to config a collection in the source registry
  docs/sourceCollections.md
Labels: documentation

#177 Update index page to organize nodes by collection name
  app-web/src/pages/index.js
  docs/sourceCollections.md
Labels: enhancement, good first issue

#180 Siphon can fetch single Github files
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSource.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/constants.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSource.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
Labels: enhancement, refactor

#178 page navigation works against collection
  app-web/gatsby/createPages.js
  app-web/src/templates/SourceGithubHTML.js
  app-web/src/templates/SourceGithubMarkdown.js
Labels: enhancement, good first issue

#182 Allow siphon to take multiple files
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
Labels: enhancement

#188 update siphon docs
  docs/images/fetchSourceGithub.png
  docs/images/siphon-simplified.png
  docs/images/story.png
  docs/siphon.md
Labels: documentation, technical debt

#190 Update Documentation for using Inline Ignores in the Registry
  docs/registerRepo.md
Labels: documentation

#189 Imp/siphon inline ignores
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js
  app-web/plugins/gatsby-source-github-all/utils/constants.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSourceGithub.js
Labels: enhancement, good first issue, technical debt

#191 Add configurations for docker, so we can develop in a consistent local env
  README.md
  app-web/.dockerignore
  app-web/Dockerfile
  app-web/package.json
Labels: documentation, pipeline, technical debt

#192 Hide page navigation if there are < 1 pages for a given collection
  app-web/src/hoc/GithubTemplateLayout.js
Labels: bug

#195 fix persona attribute for open shift components registry item
  app-web/source-registry/registry.yml
Labels: bug

#197 Refactor redux logic for filtering resources & updated tests
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/redux/siphonActionCreators.test.js
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/actions.js
  app-web/src/store/actions/siphonActions.js
  app-web/src/store/reducers/siphon.js
Labels: enhancement, refactor

#209 Update regiserRepo docs
  docs/registerRepo.md
Labels: documentation

#198 Implement UI for multi filtering
  app-web/__tests__/components/__snapshots__/CardFilterButton.test.js.snap
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/package-lock.json
  app-web/package.json
  app-web/src/assets/styles/index.css
  app-web/src/components/CardFilterButton/CardFilterButton.js
  app-web/src/components/PrimaryFilter/PrimaryFilter.js
  app-web/src/components/PrimaryFooter/PrimaryFooter.module.css
  app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
  app-web/src/components/SecondaryFilter/FilterGroup/FilterGroup.js
  app-web/src/components/SecondaryFilter/FilterGroup/FilterGroup.module.css
  app-web/src/components/SecondaryFilter/SecondaryFilter.js
  app-web/src/components/SecondaryFilter/SecondaryFilter.module.css
  app-web/src/constants/filterGroups.js
  app-web/src/pages/index.js
  app-web/src/pages/index.module.css
Labels: enhancement

#207 On click of the card filter button, it scrolls to card container
  app-web/__tests__/components/__snapshots__/CardFilterButton.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/CardFilterButton/CardFilterButton.js
  app-web/src/constants/ui.js
  app-web/src/pages/index.js
Labels: In Prod, Reviewer Wanted, enhancement

#217 Add new plugin to address relative image path issue in front matter
  app-web/__mocks__/gray-matter.js
  app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
Labels: bug

#212 Refactor constants and broke them up into seperate files in Siphon
  app-web/plugins/gatsby-source-github-all/utils/constants.js
  app-web/plugins/gatsby-source-github-all/utils/constants/index.js
  app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js
  app-web/plugins/gatsby-source-github-all/utils/constants/sourceGithub.js
  app-web/plugins/gatsby-source-github-all/utils/constants/sourceTypes.js
Labels: In Prod, Reviewer Wanted, refactor, technical debt

#219 Fixed header branding/update font
  app-web/__tests__/components/__snapshots__/AppLogo.test.js.snap
  app-web/src/assets/styles/index.css
  app-web/src/components/PrimaryFilter/PrimaryFilter.module.css
  app-web/src/components/UI/AppLogo/AppLogo.js
  app-web/src/components/UI/AppLogo/AppLogo.module.css
  app-web/src/html.js
Labels: bug

#210 Hide 'Welcome to Devhub' Message on subsequent visits
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/components/__snapshots__/CardFilterButton.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/CardFilterButton/CardFilterButton.js
  app-web/src/pages/index.js
  app-web/src/pages/index.module.css
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/actions.js
  app-web/src/store/actions/uiActions.js
  app-web/src/store/createStore.js
  app-web/src/store/reducers/ui.js
  app-web/wrapWithProvider.js
Labels: Reviewer Wanted, enhancement, good first issue

#213 Refactor Siphons Fetch Source Github File into smaller files
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSource.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSource.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/githubFileTransformer.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
Labels: Reviewer Wanted, refactor, technical debt

#221 Update Siphon documentation
  docs/siphon.md
Labels: documentation

#222 Front end refactoring
  app-web/src/components/Cards/Card/Card.module.css
  app-web/src/components/UI/Avatar/Avatar.js
  app-web/src/components/UI/Avatar/Avatar.module.css
  app-web/src/hoc/Card.js
Labels: refactor
