Repository bcgov/devhub-app-web, pull requests merged in 2019-05, with the labels that each got.

#593 Update design-system.json
  app-web/registry/design-system.json
Labels: registry:new content

#601 Update outdated NPM packages
  app-web/__fixtures__/siphon-fixtures.js
  app-web/__tests__/components/__snapshots__/CardCarousel.test.js.snap
  app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/__tests__/pages/resourceType.test.js
  app-web/gatsby-node.js
  app-web/gatsby/modifyWebpackConfig.js
  app-web/jest.config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/ComponentPreview/ComponentPreview.js
  app-web/src/components/GithubTemplate/Navigation/NavItem.js
  app-web/src/config.js
  app-web/src/config.json
  app-web/src/constants/api.js
  app-web/src/pages/about.js
Labels: task:technical debt

#607 Fix issue where octokit was not pulling repo content
  app-web/__fixtures__/markdownRemark.js
  app-web/__tests__/components/ComponentPreview.test.js
  app-web/__tests__/components/__snapshots__/ComponentPreview.test.js.snap
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/ComponentPreview/ComponentPreview.js
Labels: task:bug

#605 Add logic to re route the eventbrite feature when not available
  app-web/__fixtures__/eventbrite.js
  app-web/gatsby-node.js
  app-web/gatsby/sourceNodes.js
  app-web/src/templates/TemplatePlaceholder.js
Labels: task:bug

#621 Update index to include source name
  app-web/gatsby-config.js
Labels: task:enhancement

#623 Prevent truncation of text on cards that have whitespace to hold the text
  app-web/__tests__/components/__snapshots__/CardCarousel.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/src/components/Cards/Card/Card.js
  app-web/src/components/Cards/Card/index.js
Labels: task:ux/ui

#624 Troubleshoot underlined links on page load issue
  app-web/__tests__/components/__snapshots__/NavigationItem.test.js.snap
  app-web/src/components/NavigationItems/NavigationItem/NavigationItem.js
Labels: task:ux/ui

#627 Imp/618 deprecate GitHub repo config
  app-web/blog/removed-lazy-file-imports-from-github.md
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSource.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
  app-web/plugins/gatsby-source-github-all/utils/console.js
  app-web/plugins/gatsby-source-github-all/utils/constants/sourceTypes.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
  app-web/registry/developer-toy-box.json
  docs/README.md
  docs/components.md
  docs/featureFlags.md
  docs/registerRepo.md
  docs/registry.md
  docs/registry.sample.yml
  docs/sourceCollections.md
Labels: Devhub:V3

#631 Imp/618 integrate ids into siphon
  app-web/plugins/gatsby-source-github-all/__tests__/__snapshots__/sourceNodes.test.js.snap
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
  app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
Labels: task:enhancement, task:refactor

#612 Changed Collections to Topics and updated Unit Tests
  app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/constants/routes.js
  app-web/src/messages/index.js
Labels: task:ux/ui

#625 Nav fix for EI 11
  app-web/gatsby-config.js
  app-web/src/hoc/Layout.js
  package-lock.json
Labels: status:not ready for merge

#638 add resource
  app-web/registry/getting-started-on-the-devops-platform.json
Labels: registry:new content

#641 update packages and remove google analytics
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  docs/searching.md
Labels: task:chore

#642 Begin integration of design tokens for better UI layout control
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/src/components/CardCarousel/CardCarousel.js
  app-web/src/components/Cards/Container.js
  app-web/src/components/GithubTemplate/common.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Home/ResourcePreview.js
  app-web/src/components/Page/CardsContainer.js
  app-web/src/components/Page/FilterMenu.js
  app-web/src/constants/designTokens.js
  app-web/src/constants/ui.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
  app-web/src/templates/events.js
  app-web/theme.js
  docs/designTokens.md
Labels: task:enhancement

#637 Address Issues From SonarQube Report
  app-web/.eslintrc
  app-web/__fixtures__/siphon-fixtures.js
  app-web/__tests__/components/CardCarousel.test.js
  app-web/__tests__/components/Cards.test.js
  app-web/__tests__/components/ComponentPreview.test.js
  app-web/__tests__/components/GithubTemplateActions.test.js
  app-web/__tests__/components/NameSpacedImg.test.js
  app-web/__tests__/components/PhaseBanner.test.js
  app-web/__tests__/components/Search.test.js
  app-web/__tests__/components/SearchAwareLink.test.js
  app-web/__tests__/components/ToolsMenu.test.js
  app-web/__tests__/components/__snapshots__/CardCarousel.test.js.snap
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/__tests__/components/__snapshots__/PhaseBanner.test.js.snap
  app-web/__tests__/components/__snapshots__/Search.test.js.snap
  app-web/__tests__/components/__snapshots__/ToolsMenu.test.js.snap
  app-web/__tests__/hoc/avatarUri.test.js
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/__tests__/pages/collections.test.js
  app-web/__tests__/pages/resourceType.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/src/components/CollectionPreview/CollectionPreview.js
  app-web/src/components/GithubTemplate/common.js
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/components/Page/CardsContainer.js
  app-web/src/components/Search/index.js
  app-web/src/components/ToolsMenu/ToolsMenu.js
  app-web/src/components/UI/Avatar/Avatar.js
  app-web/src/components/UI/Avatar/Avatar.module.css
  app-web/src/components/UI/NameSpacedImg/NameSpacedImg.js
  app-web/src/components/UI/NoEvents/index.js
  app-web/src/components/UI/NoResources/NoResources.js
  app-web/src/hoc/avatarUri.js
  app-web/src/messages/index.js
  app-web/src/pages/collections.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
Labels: status:pending review, task:chore

#643 Refactor Icons for 'resource types' to be a separate react component
  app-web/__tests__/components/CardHeader.test.js
  app-web/__tests__/components/ResourceTypeIcon.test.js
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/src/components/Cards/Card/CardHeader.js
  app-web/src/components/UI/ResourceTypeIcon/index.js
Labels: task:refactor

#647 Changing replica number from 2 to 3 for OpenShift
  openshift/dc.yaml
Labels: task:pipeline, task:technical debt

#664 Creating Featured Cards topic
  app-web/__tests__/utils/helpers.test.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/registry/featured-cards.json
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/constants/topics.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/utils/helpers.js
Labels: registry:new content

#673 Update registry with 12factor apps and progressive web apps
  app-web/registry/featured-cards.json
  app-web/registry/getting-started-on-the-devops-platform.json
Labels: registry:new content

#676 Add repos to registry files
  app-web/blog/clean-coding.md
  app-web/plugins/gatsby-source-github-all/utils/registryHelpers.js
  app-web/registry/authentication-and-authorization.json
  app-web/registry/community-enablers-and-events.json
  app-web/registry/design-system.json
  app-web/registry/featured-cards.json
Labels: registry:new content
