Repository bcgov/devhub-app-web, pull requests merged in 2019-04, with the labels that each got.

#528 Add Fair Use (Image disclaimer) link to footer
  app-web/__mocks__/gatsby-link.js
  app-web/__mocks__/gatsby.js
  app-web/__tests__/components/Disclaimer.test.js
  app-web/__tests__/components/NavigationItems.test.js
  app-web/__tests__/components/PrimaryFooter.test.js
  app-web/__tests__/components/__snapshots__/Disclaimer.test.js.snap
  app-web/__tests__/components/__snapshots__/NavigationItem.test.js.snap
  app-web/__tests__/components/__snapshots__/NavigationItems.test.js.snap
  app-web/__tests__/components/__snapshots__/PrimaryFooter.test.js.snap
  app-web/__tests__/helpers.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/Disclaimer/Disclaimer.js
  app-web/src/components/NavigationItems/NavigationItem/NavigationItem.js
  app-web/src/components/NavigationItems/NavigationItems.js
  app-web/src/components/NavigationItems/NavigationItems.module.css
  app-web/src/components/PrimaryFooter/PrimaryFooter.js
  app-web/src/messages/index.js
  docs/testingAndQa.md
Labels: status:pending review, task:enhancement

#532 Upgrade Openshift s2i to use Node 10.15.3 (node 10:latest)
  README.md
  app-web/Dockerfile
  app-web/package-lock.json
  app-web/package.json
  openshift/bc.yaml
Labels: status:pending review, status:prod, task:chore, task:pipeline, task:technical debt

#537 Add general purpose selectors to be used for static renderings
  app-web/__fixtures__/siphon-fixtures.js
  app-web/__tests__/utils/selectors.test.js
  app-web/src/utils/selectors.js
Labels: Devhub:V3, status:not ready for merge, status:pending review, task:enhancement

#533 Add search react custom hook in prep for static home page
  app-web/__fixtures__/elasticlunr.js
  app-web/__tests__/utils/hooks.test.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/utils/hooks.js
Labels: Devhub:V3, task:enhancement

#539 Homepage now rendered 100% static
  Caddyfile
  app-web/__fixtures__/selector-fixtures.js
  app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Home/ResourcePreview.js
  app-web/src/components/Search/SearchPills.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/html.js
  app-web/src/pages/index.js
  app-web/src/utils/hooks.js
  app-web/src/utils/search.js
  openshift/dc.yaml
Labels: Devhub:V3, task:enhancement

#541 Collections Page now loaded 100% statically
  app-web/__tests__/components/__snapshots__/CollectionCard.test.js.snap
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/src/components/Cards/Card/CardHeader.js
  app-web/src/components/Cards/Card/Collection.js
  app-web/src/components/Cards/Card/index.js
  app-web/src/components/CollectionPreview/CollectionPreview.js
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/constants/ui.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/collections.js
Labels: Devhub:V3, status:pending review, task:enhancement

#540 Resource Template Pages now loaded 100% statically
  app-web/__fixtures__/siphon-fixtures.js
  app-web/__tests__/components/FilterGroup.test.js
  app-web/__tests__/components/__snapshots__/FilterGroup.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/__tests__/pages/resourceType.test.js
  app-web/__tests__/selectors/selectors.test.js
  app-web/gatsby/createPages.js
  app-web/src/components/Filters/FilterGroup/FilterGroup.js
  app-web/src/components/Filters/Filters.js
  app-web/src/components/UI/Input/input.module.css
  app-web/src/components/UI/NoResources/NoResources.js
  app-web/src/constants/filterGroups.js
  app-web/src/constants/search.js
  app-web/src/constants/ui.js
  app-web/src/hoc/withLocation.js
  app-web/src/pages/index.js
  app-web/src/templates/resourceType.js
  app-web/src/utils/helpers.js
Labels: Devhub:V3, status:pending review, status:prod, task:enhancement, task:ux/ui

#544 Imp/522 clean redux
  app-web/__fixtures__/lunr.js
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/actions/auth.test.js
  app-web/__tests__/actions/resource.test.js
  app-web/__tests__/actions/ui.test.js
  app-web/__tests__/components/Layout.test.js
  app-web/__tests__/components/ToolsMenu.test.js
  app-web/__tests__/components/__snapshots__/404.test.js.snap
  app-web/__tests__/components/__snapshots__/Hamburger.test.js.snap
  app-web/__tests__/components/__snapshots__/Layout.test.js.snap
  app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
  app-web/__tests__/components/__snapshots__/PrimaryHeader.test.js.snap
  app-web/__tests__/hoc/Layout.test.js
  app-web/__tests__/hoc/LayoutComponent.test.js
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/__tests__/reducers/auth.test.js
  app-web/__tests__/reducers/resource.test.js
  app-web/__tests__/reducers/ui.js
  app-web/__tests__/selectors/selectors.test.js
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/Auth/Login/Login.js
  app-web/src/components/Dropmenu/Dropmenu.js
  app-web/src/components/Navbar/Navbar.js
  app-web/src/components/PrimaryHeader/PrimaryHeader.js
  app-web/src/components/UI/GovLogo/GovLogo.js
  app-web/src/components/UI/Hamburger/Hamburger.js
  app-web/src/constants/featureflags.js
  app-web/src/hoc/Layout.js
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/auth.js
  app-web/src/store/actions/index.js
  app-web/src/store/actions/resources.js
  app-web/src/store/actions/siphon.js
  app-web/src/store/actions/ui.js
  app-web/src/store/createStore.js
  app-web/src/store/reducers/auth.js
  app-web/src/store/reducers/features.js
  app-web/src/store/reducers/resources.js
  app-web/src/store/reducers/ui.js
  app-web/src/store/selectors/collection.js
  app-web/src/store/selectors/index.js
  app-web/src/store/selectors/main.js
  app-web/src/store/selectors/resources.js
  app-web/src/templates/resourceType.js
  app-web/wrapWithProvider.js
Labels: task:technical debt

#535 Update registry.yml
  app-web/source-registry/registry.yml
Labels: registry:new content

#551 Adding dropdown component
  app-web/source-registry/registry.yml
Labels: registry:new content

#557 Spring cleaning
  app-web/__mocks__/got.js
  app-web/__mocks__/slugify.js
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-source-github-all/utils/transformer.js
Labels: task:chore, task:technical debt

#575 Imp/registry changes
  .gitignore
  app-web/devhub.config.json
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/registry/authentication-and-authorization.json
  app-web/registry/code-management.json
  app-web/registry/community-enablers-and-events.json
  app-web/registry/data-privacy.json
  app-web/registry/design-system.json
  app-web/registry/developer-tools.json
  app-web/registry/developer-toy-box.json
  app-web/registry/getting-started-on-the-devops-platform.json
  app-web/registry/information-and-application-security.json
  docs/images/card-example.png
  docs/registry.md
Labels: Devhub:V3, task:enhancement, task:technical debt

#556 adding security infographic and link to digital security site.
  app-web/registry/information-and-application-security.json
  app-web/source-registry/registry.yml
Labels: registry:new content

#576 Add doc on how devhub works
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/blog/clean-coding.md
  app-web/blog/devhub.md
  app-web/blog/starting-with-github.md
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/assets/images/Header.png
  app-web/src/assets/images/Topics.png
  app-web/src/components/Page/Main.js
  app-web/src/pages/about.js
  docs/blog/clean-coding.md
Labels: question, registry:new content

#577 integrate carousel
  app-web/__tests__/components/CardCarousel.test.js
  app-web/__tests__/components/__snapshots__/CardCarousel.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/CardCarousel/CardCarousel.js
  app-web/src/components/CollectionPreview/CollectionPreview.js
  app-web/src/constants/ui.js
  app-web/src/hoc/Card.js
  app-web/theme.js
Labels: task:ux/ui
