Repository bcgov/devhub-app-web, pull requests merged in 2019-07, with the labels that each got.

#750 Adding node fields to MarkdownRemark Nodes
  app-web/gatsby/onCreateNode.js
Labels: status:prod

#769 Chore/534 package upgrades
  app-web/__tests__/components/AppLogo.test.js
  app-web/__tests__/components/Banner.test.js
  app-web/__tests__/components/CardCarousel.test.js
  app-web/__tests__/components/ComponentPreview.test.js
  app-web/__tests__/components/Disclaimer.test.js
  app-web/__tests__/components/FilterGroup.test.js
  app-web/__tests__/components/PrimaryFooter.test.js
  app-web/__tests__/components/ResourceTypeIcon.test.js
  app-web/__tests__/components/Search.test.js
  app-web/__tests__/components/SearchAwareLink.test.js
  app-web/__tests__/components/ToolsMenu.test.js
  app-web/__tests__/helpers.js
  app-web/__tests__/hoc/LayoutComponent.test.js
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/collections.test.js
  app-web/__tests__/pages/resourceType.test.js
  app-web/__tests__/utils/hooks.test.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/GithubTemplate/SidePanel/SidePanel.js
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/components/Home/ResourcePreview.js
  app-web/src/utils/hooks.js
  docs/testingAndQa.md
Labels: task:chore

#771 Imp/add fields to gh raw
  app-web/__tests__/gatsby/gatsbyRemark.test.js
  app-web/__tests__/gatsby/getFilesFromRegistry.test.js
  app-web/__tests__/gatsby/validators.test.js
  app-web/gatsby/onCreateNode.js
  app-web/gatsby/utils/githubRaw.js
  app-web/gatsby/utils/validators.js
  app-web/package-lock.json
  app-web/package.json
  app-web/registry/data-privacy.json
  app-web/registry/developer-toy-box.json
  app-web/src/constants/ui.js
  package-lock.json
Labels: Devhub:V3

#785 Revert "Chore/534 package upgrades (#769)"
  app-web/__tests__/components/AppLogo.test.js
  app-web/__tests__/components/Banner.test.js
  app-web/__tests__/components/CardCarousel.test.js
  app-web/__tests__/components/ComponentPreview.test.js
  app-web/__tests__/components/Disclaimer.test.js
  app-web/__tests__/components/FilterGroup.test.js
  app-web/__tests__/components/PrimaryFooter.test.js
  app-web/__tests__/components/ResourceTypeIcon.test.js
  app-web/__tests__/components/Search.test.js
  app-web/__tests__/components/SearchAwareLink.test.js
  app-web/__tests__/components/ToolsMenu.test.js
  app-web/__tests__/helpers.js
  app-web/__tests__/hoc/LayoutComponent.test.js
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/collections.test.js
  app-web/__tests__/pages/resourceType.test.js
  app-web/__tests__/utils/hooks.test.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/GithubTemplate/SidePanel/SidePanel.js
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/components/Home/ResourcePreview.js
  app-web/src/utils/hooks.js
  docs/testingAndQa.md
Labels: task:bug

#779 Only build component if there are changes associated with current Jenkinsfile
  Jenkinsfile
  matomo/Jenkinsfile
Labels: Don't promote

#817 Upgrade packages
  app-web/package-lock.json
  app-web/package.json
Labels: status:pending review, status:prod, task:chore, task:technical debt

#816 Integrate resource type via fields
  app-web/__fixtures__/siphon-fixtures.js
  app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
  app-web/gatsby-config.js
  app-web/gatsby/onCreateNode.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/templates/events.js
  app-web/src/utils/selectors.js
Labels: Devhub:V3, status:pending review

#818 Imp/v3 order preservation
  app-web/.eslintignore
  app-web/__tests__/gatsby/getFilesFromRegistry.test.js
  app-web/gatsby/utils/githubRaw.js
Labels: Devhub:V3

#782 Work towards speeding up builds via use of incremental build.
  README.md
  app-web/.s2i/bin/assemble
  app-web/blog/devhub.md
  docker-images/nodejs-base/Dockerfile
  docker-images/nodejs-base/package-lock.json
  docker-images/nodejs-base/package.json
  openshift/templates/bc.yaml
Labels: Don't promote

#827 Imp/build gh raw node pages
  app-web/__fixtures__/nodes.js
  app-web/__tests__/components/ResourcePreview.test.js
  app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/__tests__/pages/resourceType.test.js
  app-web/__tests__/pages/topics.test.js
  app-web/__tests__/utils/__snapshots__/selectors.test.js.snap
  app-web/__tests__/utils/selectors.test.js
  app-web/gatsby/createPages.js
  app-web/gatsby/createResolvers.js
  app-web/gatsby/onCreateNode.js
  app-web/src/components/GithubTemplate/Navigation/NavGroup.js
  app-web/src/components/GithubTemplate/Navigation/NavItem.js
  app-web/src/components/GithubTemplate/Navigation/Navigation.js
  app-web/src/components/Home/ResourcePreview.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/index.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
  app-web/src/templates/resourceType.js
  app-web/src/utils/helpers.js
  app-web/src/utils/hooks.js
  app-web/src/utils/selectors.js
Labels: Devhub:V3

#825 Bug fix for mobile Side Drawer
  app-web/__tests__/components/__snapshots__/Sidedrawer.test.js.snap
  app-web/package-lock.json
  app-web/src/components/SideDrawer/SideDrawer.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
  app-web/src/templates/resourceType.js
Labels: task:bug

#835 Adding GitHub workflow to execute unit tests.
  .github/main.workflow
  app-web/shell-scripts/unit-tests.sh
Labels: Don't promote

#837 add matomo api secret
  app-web/.env.production.example
  app-web/package-lock.json
  app-web/package.json
  openshift/templates/matomo.secret.yaml
Labels: task:enhancement

#841 Update docs to explain matomo env var usage
  README.md
Labels: task:documentation

#836 add location services guide
  app-web/registry/community-contributed.json
Labels: registry:new content

#844 Fix a bug where markdown previews were not working
  app-web/src/components/ComponentPreview/ComponentPreview.js
Labels: task:bug

#829 Adding s2i scripts to enable incremental builds
  app-web/.s2i/bin/assemble
  app-web/.s2i/bin/save-artifacts
  app-web/shell-scripts/s2i-build-incremental.sh
  openshift/templates/bc.yaml
Labels: Don't promote

#849 Imp/integrate popular topic
  app-web/__fixtures__/nodes.js
  app-web/__tests__/components/CardCarousel.test.js
  app-web/__tests__/components/FilterGroup.test.js
  app-web/__tests__/components/PopularTopic.test.js
  app-web/__tests__/components/__snapshots__/PopularTopic.test.js.snap
  app-web/__tests__/gatsby/getFilesFromRegistry.test.js
  app-web/__tests__/pages/__snapshots__/topics.test.js.snap
  app-web/__tests__/pages/topics.test.js
  app-web/__tests__/utils/__snapshots__/selectors.test.js.snap
  app-web/__tests__/utils/helpers.test.js
  app-web/__tests__/utils/selectors.test.js
  app-web/gatsby/createResolvers.js
  app-web/gatsby/createSchemaCustomization.js
  app-web/gatsby/onCreateNode.js
  app-web/gatsby/utils/githubRaw.js
  app-web/gatsby/utils/validators.js
  app-web/package.json
  app-web/src/components/CardCarousel/CardCarousel.js
  app-web/src/components/GithubTemplate/Navigation/Navigation.js
  app-web/src/components/Home/TopicsContainer.js
  app-web/src/components/PopularTopic/index.js
  app-web/src/hoc/Layout.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/index.js
  app-web/src/pages/topic.js
  app-web/src/pages/topics.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
  app-web/src/utils/helpers.js
  app-web/topics/popular.md
  docs/howNodesAreConnected.md
Labels: status:pending review, status:prod

#871 Add redhat security symposium event
  app-web/registry/community-and-events.json
Labels: status:prod
