Repository bcgov/devhub-app-web, pull requests merged in 2019-06, with the labels that each got.

#679 improve spacing of Masthead in homepage
  app-web/__tests__/components/ResourceTypeIcon.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/src/components/GithubTemplate/Masthead/Masthead.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Page/CardsContainer.js
  app-web/src/components/Page/FilterMenu.js
  app-web/src/components/Page/Main.js
  app-web/src/components/Page/PageContainer.js
  app-web/src/components/Page/Title.js
  app-web/src/components/Page/index.js
  app-web/src/constants/designTokens.js
  app-web/src/pages/collections.js
  app-web/src/pages/index.js
  app-web/src/templates/events.js
  app-web/src/templates/resourceType.js
Labels: task:technical debt, task:ux/ui

#680 Update featured-cards.json
  app-web/registry/featured-cards.json
Labels: registry:new content

#678 Community Contributed Content
  app-web/registry/community-contributed.json
  app-web/registry/developer-toy-box.json
Labels: registry:new content

#697 Imp/jenkins upgrade
  .jenkins/.pipeline/build.js
  .jenkins/.pipeline/clean.js
  .jenkins/.pipeline/deploy.js
  .jenkins/.pipeline/lib/build.js
  .jenkins/.pipeline/lib/clean.js
  .jenkins/.pipeline/lib/config.js
  .jenkins/.pipeline/lib/deploy.js
  .jenkins/.pipeline/npmw
  .jenkins/.pipeline/package-lock.json
  .jenkins/.pipeline/package.json
  .jenkins/Jenkinsfile
  .jenkins/README.md
  .jenkins/docker/Dockerfile
  .jenkins/docker/contrib/jenkins/configuration/jobs/_jenkins/config.xml
  .jenkins/openshift/build-master.yaml
  .jenkins/openshift/build-slave.yaml
  .jenkins/openshift/deploy-master.yaml
  .jenkins/openshift/deploy-prereq.yaml
  .jenkins/openshift/deploy-slave.yaml
  .jenkins/openshift/secrets.json
  .yo-rc.json
Labels: task:pipeline

#706 Renaming featured cards topic
  app-web/__tests__/utils/helpers.test.js
  app-web/registry/featured-resources.json
  app-web/src/constants/topics.js
  app-web/src/utils/helpers.js
Labels: task:ux/ui

#714 add validators functions to be used on node field creations
  app-web/gatsby/validators.js
Labels: Devhub:V3

#717 Content - Topic Data and Apis'
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/registry/data-and-apis.json
  app-web/registry/featured-resources.json
Labels: registry:new content, status:prod

#740 Fix Issue where events page breaks if events are private
  app-web/__fixtures__/siphon-fixtures.js
  app-web/gatsby-config.js
  app-web/gatsby-node.js
  app-web/gatsby/createResolvers.js
  app-web/gatsby/onCreateNode.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/Event/Logo.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/collections.js
  app-web/src/templates/events.js
Labels: task:bug

#745 re enable meetup plugin for ux guild
  app-web/gatsby-config.js
Labels: task:enhancement

#747 Imp/markdown path transformer upgrade
  app-web/__tests__/gatsby-plugins/gatsby-remark-transform-path.test.js
  app-web/__tests__/utils/gatsbyRemark.test.js
  app-web/package-lock.json
  app-web/plugins/gatsby-remark-path-transform/README.md
  app-web/plugins/gatsby-remark-path-transform/__tests__/utils.test.js
  app-web/plugins/gatsby-remark-path-transform/index.js
  app-web/plugins/gatsby-remark-path-transform/package.json
  app-web/src/utils/gatsbyRemark.js
  docs/gatsby-custom-plugins/gatsby-remark-path-transform.md
Labels: status:prod, task:enhancement

#749 Add markdown node to path transformer plugin as a utility
  app-web/__fixtures__/plugin-fixtures.js
  app-web/__tests__/gatsby-plugins/gatsby-remark-transform-path.test.js
  app-web/__tests__/utils/gatsbyRemark.test.js
  app-web/plugins/gatsby-remark-path-transform/__tests__/utils.test.js
  app-web/plugins/gatsby-remark-path-transform/index.js
  app-web/src/utils/gatsbyRemark.js
  docs/gatsby-custom-plugins/gatsby-remark-path-transform.md
Labels: Devhub:V3
