Repository bcgov/devhub-app-web, pull requests merged in 2019-02, with the labels that each got.

#345 Add a react link component that sets active class based on search params
  app-web/__tests__/components/SearchAwareLink.test.js
  app-web/src/components/UI/Link/SearchAwareLink.js
  app-web/src/components/UI/Link/index.js
Labels: enhancement, pending review, ux/ui

#338 Code Cleanup/Resolving Technical Debt on the frontend
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/__tests__/components/__snapshots__/Search.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/redux/siphonActionCreators.test.js
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/__tests__/redux/uiActionCreators.test.js
  app-web/__tests__/redux/uiReducer.test.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/Cards/Card/ActionsRibbon.js
  app-web/src/components/Cards/Card/ComponentCard.js
  app-web/src/components/Cards/Card/DocumentCard.js
  app-web/src/components/Cards/Card/RepositoryCard.js
  app-web/src/components/Search/Search.js
  app-web/src/components/SecondaryFilter/SecondaryFilter.js
  app-web/src/components/ToolsMenu/FilterMenu/FilterMenu.js
  app-web/src/components/ToolsMenu/SearchFeedback/SearchFeedback.js
  app-web/src/components/ToolsMenu/ToolsMenu.js
  app-web/src/components/UI/Button/Button.js
  app-web/src/components/UI/Button/Button.module.css
  app-web/src/pages/index.js
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/actions.js
  app-web/src/store/actions/siphonActions.js
  app-web/src/store/actions/uiActions.js
  app-web/src/store/reducers/siphon.js
  app-web/src/store/reducers/ui.js
Labels: not ready for merge, technical debt

#360 Adjust max width of markdown page content container
  app-web/src/templates/SourceMarkdown.module.css
Labels: ux/ui

#376 Improve tech debt for search feature
  app-web/__mocks__/gatsby-link.js
  app-web/__tests__/components/ToolsMenu.test.js
  app-web/src/components/Search/Search.js
Labels: technical debt

#378 Imp/design system order
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/source-registry/registry.yml
  app-web/src/components/GithubTemplate/SourceNavigation/SourceNavigation.js
  app-web/src/store/reducers/siphon.js
Labels: In Prod, bug, reviewer wanted, ux/ui

#383 bugs/380-381-componentpreview-bugs
  app-web/__tests__/components/__snapshots__/ComponentPreview.test.js.snap
  app-web/src/components/ComponentPreview/ComponentPreview.js
Labels: In Prod

#388 Add Unit Tests to reselect Selectors
  app-web/__fixtures__/redux-fixtures.js
  app-web/__fixtures__/siphon-fixtures.js
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/redux/selectors.test.js
  app-web/src/store/selectors/index.js
Labels: technical debt

#386 Refactor Siphon reducer and Apply memoization techniques for optimization of sorting/filtering
  app-web/__fixtures__/lunr.js
  app-web/__fixtures__/redux-fixtures.js
  app-web/__fixtures__/siphon-fixtures.js
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/redux/selectors.test.js
  app-web/__tests__/redux/siphonActionCreators.test.js
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/ToolsMenu/SearchFeedback/SearchFeedback.js
  app-web/src/components/ToolsMenu/ToolsMenu.js
  app-web/src/pages/index.js
  app-web/src/store/reducers/siphon.js
  app-web/src/store/selectors/index.js
Labels: In Prod, refactor, technical debt

#392 Siphon Supports Collection Overview Content
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/console.js
  app-web/plugins/gatsby-source-github-all/utils/constants/registry.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
  app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
  app-web/source-registry/__fixtures__/registry.yml
Labels: enhancement

#390 Add docs for collection pages
  docs/registerRepo.md
  docs/siphon.md
  docs/sourceCollections.md
Labels: documentation

#394 Fix bug where search state was maintained across pages
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/redux/siphonActionCreators.test.js
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/src/pages/index.js
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/actions.js
  app-web/src/store/actions/siphonActions.js
  app-web/src/store/reducers/siphon.js
Labels: bug

#413 Add ability to leverage react avatar using a uri
  app-web/__tests__/components/NameSpacedImg.test.js
  app-web/__tests__/hoc/avatarUri.test.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/UI/NameSpacedImg/NameSpacedImg.js
  app-web/src/constants/ui.js
  app-web/src/hoc/avatarUri.js
Labels: enhancement

#414 Modify deploy and build configs for requests and timeouts
  openshift/bc.yaml
  openshift/dc.yaml
Labels: pipeline

#419 Imp/docker compose
  .gitignore
  README.md
  app-web/Dockerfile
  docker-compose.yml
Labels: technical debt

#422 Imp/beautify css
  app-web/.jsbeautifyrc
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/ComponentPreview/ComponentPreview.js
  app-web/src/components/UI/GovLogo/GovLogo.js
  app-web/src/pages/index.module.css
  docs/blog/clean-coding.md
Labels: technical debt

#431 Imp/tech debt
  app-web/__tests__/components/MetadataRibbon.js
  app-web/__tests__/components/Sidedrawer.test.js
  app-web/__tests__/components/__snapshots__/Sidedrawer.test.js.snap
  app-web/src/components/SideDrawer/SideDrawer.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
Labels: technical debt

#436 Clean up siphon reducer
  app-web/__tests__/redux/siphonActionCreators.test.js
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/__tests__/utils/dataHelpers.test.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/Filters/Filters.js
  app-web/src/pages/index.js
  app-web/src/store/createStore.js
  app-web/src/store/reducers/siphon.js
  app-web/src/store/selectors/index.js
  app-web/src/utils/dataHelpers.js
Labels: technical debt

#437 Abstract 'devhubSiphon' query into a reusable component
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/index.js
Labels: enhancement
