Repository bcgov/devhub-app-web, pull requests merged in 2019-03, with the labels that each got.

#432 Imp/sidedrawer transition
  app-web/__tests__/components/Sidedrawer.test.js
  app-web/__tests__/components/__snapshots__/Sidedrawer.test.js.snap
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/SideDrawer/SideDrawer.js
  app-web/src/components/UI/Backdrop/Backdrop.js
Labels: ux/ui

#448 Imp/devex logo
  app-web/__tests__/components/__snapshots__/NavigationItems.test.js.snap
  app-web/src/assets/images/devex.svg
  app-web/src/components/NavigationItems/NavigationItems.js
  app-web/src/components/PrimaryFooter/PrimaryFooter.js
  app-web/src/components/PrimaryFooter/PrimaryFooter.module.css
  app-web/src/store/selectors/index.js
Labels: good first issue

#446 Refactor Search Function and combine partial/full searching to get better search results
  app-web/src/pages/index.js
  app-web/src/templates/resourceType.js
  app-web/src/utils/helpers.js
Labels: bug

#451 Add Collections Page
  app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
  app-web/__tests__/pages/__snapshots__/collections.test.js.snap
  app-web/__tests__/pages/collections.test.js
  app-web/src/components/CollectionPreview/CollectionPreview.js
  app-web/src/components/Page/CollectionsContainer.js
  app-web/src/constants/routes.js
  app-web/src/messages/index.js
  app-web/src/pages/collections.js
  app-web/src/templates/resourceType.js
  app-web/src/utils/helpers.js
Labels: enhancement, pending review, ux/ui

#460 Reorder main navigation links
  app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
  app-web/src/constants/routes.js
Labels: ux/ui

#473 Bug/search feedback
  app-web/__tests__/components/Search.test.js
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/utils/helpers.test.js
  app-web/src/components/Page/CardsContainer.js
  app-web/src/components/Search/Search.js
  app-web/src/pages/index.js
  app-web/src/store/selectors/index.js
  app-web/src/store/selectors/resources.js
  app-web/src/templates/resourceType.js
  app-web/src/utils/helpers.js
Labels: bug, pending review

#479 Update packages
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/collections.test.js
  app-web/gatsby/createPages.js
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/collections.js
  app-web/src/pages/index.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
  app-web/src/templates/resourceType.js
  docs/siphon.md
Labels: major update

#474 Feat/470 GitHub issues
  app-web/__tests__/components/GithubTemplateActions.test.js
  app-web/__tests__/components/Link.test.js
  app-web/__tests__/components/__snapshots__/Banner.test.js.snap
  app-web/src/components/GithubTemplate/Actions/Actions.js
  app-web/src/components/GithubTemplate/Navigation/NavItem.js
  app-web/src/components/UI/Banner/Banner.js
  app-web/src/components/UI/Banner/Banner.module.css
  app-web/src/components/UI/Link/ChevronLink.js
  app-web/src/components/UI/Link/Link.js
  app-web/src/html.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
  app-web/src/templates/SourceMarkdown.module.css
  app-web/src/utils/helpers.js
Labels: enhancement, pending review, ux/ui

#483 Docs/search
  docs/searching.md
Labels: documentation

#476 Bug/463 view all collections
  app-web/__tests__/components/ResourcePreview.test.js
  app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/src/components/Home/CollectionsContainer.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Home/ResourcePreview.js
  app-web/src/components/Home/index.js
  app-web/src/components/ResourcePreview/ResourcePreview.module.css
  app-web/src/pages/index.js
Labels: status:pending review, task:bug

#480 Add Pill Component
  app-web/__tests__/components/Pill.test.js
  app-web/src/components/UI/Pill/index.js
Labels: good first issue, story:search

#487 Remove slack page from registry
  app-web/source-registry/registry.yml
Labels: registry:new content

#478 Bug/471 typography
  app-web/.jsbeautifyrc
  app-web/src/components/Cards/Card/index.js
  app-web/src/components/Home/index.js
  app-web/src/components/Page/Title.js
  app-web/src/components/Page/Title.module.css
  app-web/src/components/UI/AppLogo/AppLogo.module.css
  app-web/src/components/UI/Banner/Banner.module.css
  app-web/src/components/UI/Input/input.module.css
  app-web/src/html.js
Labels: status:pending review, status:prod, task:bug

#493 Change Navigation label from All to Home
  app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
  app-web/src/components/Navbar/Navbar.module.css
  app-web/src/components/PrimaryHeader/PrimaryHeader.module.css
  app-web/src/constants/routes.js
  app-web/src/hoc/Layout.js
Labels: task:ux/ui

#489 add offline support as well as a manifest file in an effort to improv…
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/html.js
  app-web/static/images/favicon.ico
Labels: status:pending review, task:technical debt

#492 Bug/jest watch
  app-web/package-lock.json
  app-web/package.json
Labels: task:technical debt

#481 Refactor search portions of the resources reducer
  app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
  app-web/__tests__/redux/resourceReducer.test.js
  app-web/__tests__/redux/selectors.test.js
  app-web/src/components/Cards/Card/Card.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Navbar/Navbar.js
  app-web/src/components/Page/CardsContainer.js
  app-web/src/pages/index.js
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/resources.js
  app-web/src/store/reducers/resources.js
  app-web/src/store/selectors/index.js
  app-web/src/store/selectors/resources.js
  app-web/src/templates/resourceType.js
Labels: status:pending review, story:search, task:refactor, task:technical debt

#490 Search Feedback and Resetting
  app-web/__tests__/components/Search.test.js
  app-web/__tests__/components/__snapshots__/Search.test.js.snap
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/utils/helpers.test.js
  app-web/__tests__/utils/search.test.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Home/Masthead.module.css
  app-web/src/components/Page/CardsContainer.js
  app-web/src/components/Search/Search.module.css
  app-web/src/components/Search/SearchFeedback/SearchFeedback.js
  app-web/src/components/Search/SearchPills.js
  app-web/src/components/Search/index.js
  app-web/src/components/ToolsMenu/ToolsMenu.js
  app-web/src/components/UI/Pill/index.js
  app-web/src/pages/index.js
  app-web/src/store/actions/index.js
  app-web/src/store/reducers/resources.js
  app-web/src/store/selectors/resources.js
  app-web/src/templates/resourceType.js
  app-web/src/utils/helpers.js
  app-web/src/utils/search.js
Labels: status:pending review, story:search, task:enhancement, task:ux/ui

#495 Bug/462 homepage search
  app-web/.eslintrc
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/src/pages/index.js
Labels: task:bug, task:ux/ui

#503 set OCP-pipeline to version 0.0.6
  Jenkinsfile
Labels: task:pipeline

#504 Seperate 'store' unit tests into their respective folders
  app-web/__tests__/actions/auth.test.js
  app-web/__tests__/actions/resource.test.js
  app-web/__tests__/actions/ui.test.js
  app-web/__tests__/reducers/auth.test.js
  app-web/__tests__/reducers/resource.test.js
  app-web/__tests__/reducers/ui.js
  app-web/__tests__/selectors/selectors.test.js
Labels: task:technical debt

#508 Add better key cloak logo from a more reliable source (github)
  app-web/source-registry/registry.yml
Labels: task:bug

#509 Bug/496 external link behaviour
  app-web/src/components/GithubTemplate/Navigation/NavItem.js
Labels: task:bug

#510 change unfurl image to be gov logo
  app-web/src/html.js
  app-web/static/connected.png/connected.png
  app-web/static/images/connected.png
  app-web/static/images/gov-logo-static.png
Labels: task:chore
