Repository bcgov/devhub-app-web, pull requests merged in 2019-01, with the labels that each got.

#224 Integrate Lunr Search into the App (no UI changes on this PR)
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-source-github-all/utils/constants/sourceGithub.js
Labels: In Prod, enhancement

#215 remove prop type error on PrimaryFilter
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/src/components/Cards/Cards.js
  app-web/src/components/PrimaryFilter/PrimaryFilter.js
  app-web/src/constants/ui.js
Labels: good first issue, refactor, technical debt

#214 Add source type 'web' so that siphon can suck up information from a website
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceWeb.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
  app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js
  app-web/plugins/gatsby-source-github-all/utils/constants/sourceTypes.js
  app-web/plugins/gatsby-source-github-all/utils/fetchSource.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
  app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
Labels: Reviewer Wanted, enhancement

#230 Doc/web source types
  docs/images/samplecard.png
  docs/images/simple-github-source.jpeg
  docs/registerRepo.md
  docs/registry.sample.yml
Labels: documentation

#234 Client Side Refactorings #3
  app-web/__tests__/components/__snapshots__/Layout.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/src/components/Dropmenu/Dropmenu.js
  app-web/src/components/FilterMenu/FilterMenu.js
  app-web/src/components/FilterMenu/FilterMenu.module.css
  app-web/src/components/SecondaryFilter/SecondaryFilter.js
  app-web/src/components/SecondaryFilter/SecondaryFilter.module.css
  app-web/src/components/Sidebar/Sidebar.js
  app-web/src/components/Sidebar/Sidebar.module.css
  app-web/src/constants/featureflags.js
  app-web/src/hoc/Layout.js
  app-web/src/pages/index.js
  app-web/src/pages/index.module.css
  app-web/src/store/reducers/features.js
Labels: refactor

#236 fix broken hamburger
  app-web/__tests__/components/__snapshots__/Layout.test.js.snap
  app-web/src/hoc/Layout.js
  app-web/src/pages/index.js
Labels: bug

#235 Adjust Markdown Styling
  app-web/package-lock.json
  app-web/package.json
  app-web/src/templates/SourceGithubMarkdown.js
  app-web/src/templates/SourceMarkdown.module.css
Labels: enhancement

#240 Move client side filtering to allow for fiiltering by a 1 to many relationship
  app-web/__fixtures__/redux-fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/src/store/reducers/siphon.js
Labels: enhancement

#241 Revert Filter Components into Index Page From Layout Component
  app-web/__tests__/components/__snapshots__/Layout.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/src/hoc/Layout.js
  app-web/src/pages/index.js
Labels: refactor

#247 Imp/siphon multiple personas
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
  app-web/source-registry/registry.yml
  app-web/src/constants/filterGroups.js
  app-web/src/pages/index.js
Labels: enhancement

#264 Broken Absolute/Relative Links in MD Files
  app-web/__fixtures__/plugin-fixtures.js
  app-web/__tests__/gatsby-plugins/gatsby-remark-transform-path.test.js
  app-web/__tests__/utils/utils.test.js
  app-web/gatsby-config.js
  app-web/plugins/gatsby-remark-path-transform/__tests__/utils.test.js
  app-web/plugins/gatsby-remark-path-transform/index.js
  app-web/plugins/gatsby-remark-path-transform/utils/utils.js
  app-web/src/utils/gatsby-remark-transform-path.js
Labels: In Prod, bug

#265 Siphon Collections as a first class object ( pr 1 of n)
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js
  app-web/src/utils/gatsby-remark-transform-path.js
Labels: In Prod, enhancement

#266 Siphon Collections as a First class object ( pr 2 of n)
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
Labels: enhancement

#267 Siphon Collections as First Class Object (pr 3 of n)
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
Labels: In Prod, enhancement

#273 Fix docker permissions
  app-web/Dockerfile
Labels: bug

#277 Fix broken anchored header links
  app-web/plugins/gatsby-remark-path-transform/index.js
Labels: bug

#275 Add support for collection descriptions
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
Labels: In Prod, Reviewer Wanted, enhancement

#276 Implicitly add github repository descriptions when source collection is github
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceGithub.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/api.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/index.js
Labels: In Prod, enhancement

#281 update docs to reflect changes to the collections schema
  docs/registerRepo.md
  docs/siphon.md
  docs/sourceCollections.md
Labels: documentation, technical debt

#279 Integrate siphon collections into Front End
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/components/Cards.test.js
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/redux/siphonActionCreators.test.js
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/src/components/Cards/Cards.js
  app-web/src/components/PrimaryFilter/PrimaryFilter.js
  app-web/src/constants/filterGroups.js
  app-web/src/pages/index.js
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/actions.js
  app-web/src/store/actions/siphonActions.js
  app-web/src/store/reducers/siphon.js
Labels: refactor

#288 Add documentation for siphon node changes
  docs/siphon.md
Labels: documentation, technical debt

#284 Devhub has collection/repo descriptions
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/src/components/Cards/Cards.js
  app-web/src/components/Cards/Cards.module.css
  app-web/src/pages/index.js
Labels: In Prod, enhancement

#286 Fix card show more/less toggle button to render an appropriate number of cards in groups of 3
  app-web/__tests__/components/Cards.test.js
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/src/components/Cards/Cards.js
  app-web/src/constants/ui.js
Labels: good first issue, ux/ui

#290 implement siphon node sorting by position
  app-web/__fixtures__/redux-fixtures.js
  app-web/__tests__/components/__snapshots__/Cards.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/package-lock.json
  app-web/plugins/gatsby-remark-path-transform/index.js
  app-web/src/pages/index.js
  app-web/src/store/reducers/siphon.js
Labels: In Prod, enhancement, ux/ui

#294 Integrate collection templates based on type
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/constants/registry.js
  app-web/plugins/gatsby-source-github-all/utils/constants/siphonNode.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/source-registry/registry.yml
Labels: enhancement

#295 Add an 'overview' template as proof of concept for Collection Templating
  app-web/gatsby/createPages.js
  app-web/source-registry/registry.yml
  app-web/src/components/Collection/Overview.js
  app-web/src/components/Collection/Overview.module.css
  app-web/src/components/GithubTemplate/Header/Header.js
  app-web/src/components/GithubTemplate/Header/Header.module.css
  app-web/src/components/GithubTemplate/SidePanel/SidePanel.js
  app-web/src/components/GithubTemplate/SidePanel/SidePanel.module.css
  app-web/src/components/GithubTemplate/SourceNavigation/SourceNavigation.js
  app-web/src/components/GithubTemplate/SourceNavigation/SourceNavigation.module.css
  app-web/src/hoc/GithubTemplateLayout.js
  app-web/src/hoc/TemplateLayout.module.css
  app-web/src/templates/SourceGithubHTML.js
  app-web/src/templates/SourceGithub_default.js
  app-web/src/templates/SourceGithub_overview.js
  app-web/src/templates/SourceMarkdown.module.css
Labels: In Prod, enhancement, ux/ui

#297 Docs/siphon templates
  docs/registerRepo.md
  docs/siphon.md
  docs/sourceCollections.md
Labels: documentation, technical debt

#303 Make Print css optimizations
  app-web/src/assets/styles/index.css
  app-web/src/components/GithubTemplate/SidePanel/SidePanel.module.css
  app-web/src/components/PrimaryFooter/PrimaryFooter.module.css
Labels: bug

#313 Rename siphon reducer state members
  app-web/__tests__/redux/siphonReducer.test.js
  app-web/src/pages/index.js
  app-web/src/store/reducers/siphon.js
Labels: In Prod, technical debt

#315 Siphon node now has references to parent collection
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  docs/siphon.md
Labels: enhancement

#317 Ability to override unfurl properties
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceWeb.itest.js
  app-web/plugins/gatsby-source-github-all/__tests__/fetchSourceWeb.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/helpers.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
  app-web/plugins/gatsby-source-github-all/utils/constants/sourceTypes.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
  docs/registerRepo.md
Labels: In Prod, enhancement

#318 Allow registry items to have a slug property to control page path urls
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-source-github-all/__fixtures__/fixtures.js
  app-web/plugins/gatsby-source-github-all/__tests__/Store.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/Store.js
  app-web/plugins/gatsby-source-github-all/utils/constants/registry.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  docs/registerRepo.md
Labels: enhancement

#320 Markdown files can provide the `slug` front matter property
  app-web/__mocks__/slugify.js
  app-web/__mocks__/valid-url.js
  app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
  app-web/plugins/gatsby-source-github-all/__tests__/transformer.itest.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/constants/sourceGithub.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/plugins/gatsby-source-github-all/utils/sources/github/githubFileTransformer.js
  app-web/source-registry/registry.yml
  docs/registerRepo.md
Labels: Not ready for merge, enhancement

#321 Relative page links map to internal pages if they exist
  app-web/__fixtures__/plugin-fixtures.js
  app-web/__tests__/components/__snapshots__/ActionRibbon.test.js.snap
  app-web/__tests__/components/__snapshots__/Banner.test.js.snap
  app-web/__tests__/components/__snapshots__/Card.test.js.snap
  app-web/__tests__/components/__snapshots__/NavigationItem.test.js.snap
  app-web/__tests__/components/__snapshots__/PrimaryFilter.test.js.snap
  app-web/__tests__/gatsby-plugins/gatsby-remark-transform-path.test.js
  app-web/__tests__/utils/utils.test.js
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
  app-web/plugins/gatsby-remark-path-transform/__tests__/utils.test.js
  app-web/plugins/gatsby-remark-path-transform/index.js
  app-web/plugins/gatsby-source-github-all/__tests__/sourceNodes.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/createNode.js
  app-web/src/components/GithubTemplate/SourceNavigation/SourceNavigation.js
  app-web/src/components/GithubTemplate/SourceNavigation/SourceNavigation.module.css
  app-web/src/components/UI/Link/Link.js
  app-web/src/components/UI/PhaseBanner/PhaseBanner.js
  app-web/src/utils/gatsby-remark-transform-path.js
  docs/gatsby-custom-plugins/gatsby-remark-path-transform.md
Labels: In Prod, enhancement, pending review, reviewer wanted

#327 Fix siphon failing when trying to unfurl sites that have no metadata
  app-web/plugins/gatsby-source-github-all/__tests__/transfomer.test.js
  app-web/plugins/gatsby-source-github-all/sourceNodes.js
  app-web/plugins/gatsby-source-github-all/utils/console.js
  app-web/plugins/gatsby-source-github-all/utils/helpers.js
  app-web/plugins/gatsby-source-github-all/utils/plugins.js
  app-web/plugins/gatsby-source-github-all/utils/sources/web/index.js
Labels: In Prod, bug, pending review, reviewer wanted

#322 fix a bug where smaller images wouldn't center in the cards
  app-web/src/components/Cards/Card/Card.module.css
Labels: In Prod, bug, good first issue, reviewer wanted

#330 add Search component based on spec
  app-web/__tests__/components/Search.test.js
  app-web/__tests__/components/__snapshots__/Search.test.js.snap
  app-web/src/components/Search/Search.js
Labels: In Prod, enhancement, ux/ui

#344 provide a mechanism for primary filter links to be aware of url param…
  app-web/__tests__/components/__snapshots__/PrimaryFilter.test.js.snap
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/src/components/Navigation/PrimaryFilter.js
  app-web/src/components/ToolsMenu/ToolsMenu.js
  app-web/src/store/actions/actionTypes.js
  app-web/src/store/actions/actions.js
  app-web/src/store/actions/siphonActions.js
  app-web/src/store/reducers/siphon.js
Labels: In Prod, bug
