Repository bcgov/devhub-app-web, pull requests merged in 2020-03, with the labels that each got.

#1296 locally cache remote image references to speedup page performance
  app-web/gatsby-config.js
  app-web/gatsby/createSchemaCustomization.js
  app-web/gatsby/onCreateNode.js
  app-web/src/components/Card/Card.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/index.js
  app-web/src/utils/hooks.js
Labels: task: enhancement

#1300 Add Algolia blog
  app-web/src/assets/blog/integratingAlgolia.md
  app-web/src/assets/images/algolia-metrics-example.png
Labels: task: documentation

#1315 Persona Pill Resources
  algolia/index.json
  app-web/__tests__/utils/algolia.test.js
  app-web/src/templates/StandAlone_GitHubRaw.js
  app-web/src/utils/algolia.js
  app-web/src/utils/hooks.js
Labels: task: bug

#1322 adding collaboration tools topic.
  .github/workflows/devhub-markdown-test.yaml
  app-web/gatsby-config.js
  app-web/topicRegistry/collaboration-tools.json
  app-web/topicRegistry/platform-service-migration.json
  app-web/topics/collaboration-tools.md
Labels: task: new content

#1320 added human help doc
  app-web/topicRegistry/getting-started-on-the-devops-platform.json
Labels: task: new content

#1337 Removing Collaboration tools topic
  app-web/topicRegistry/collaboration-tools.json
  app-web/topics/collaboration-tools.md
Labels: priority: high, task: operational
