Repository bcgov/devhub-app-web, pull requests merged in 2020-01, with the labels that each got.

#1207 Action/frontmatter
  .github/actions/devhub-markdown-frontmatter-verify/.eslintignore
  .github/actions/devhub-markdown-frontmatter-verify/.eslintrc
  .github/actions/devhub-markdown-frontmatter-verify/.prettierignore
  .github/actions/devhub-markdown-frontmatter-verify/.prettierrc
  .github/actions/devhub-markdown-frontmatter-verify/README.md
  .github/actions/devhub-markdown-frontmatter-verify/action.yml
  .github/actions/devhub-markdown-frontmatter-verify/dist/index.js
  .github/actions/devhub-markdown-frontmatter-verify/jest.config.js
  .github/actions/devhub-markdown-frontmatter-verify/package-lock.json
  .github/actions/devhub-markdown-frontmatter-verify/package.json
  .github/actions/devhub-markdown-frontmatter-verify/src/__tests__/index.test.js
  .github/actions/devhub-markdown-frontmatter-verify/src/index.js
  .github/actions/devhub-markdown-frontmatter-verify/src/run.js
  .github/actions/devhub-markdown-frontmatter-verify/src/strings.js
  .github/actions/devhub-markdown-frontmatter-verify/src/utils.js
  .github/actions/devhub-markdown-frontmatter-verify/src/validators.js
  .github/actions/devhub-markdown-frontmatter-verify/webpack.config.js
  .github/workflows/devhub-markdown-test.yaml
  .gitignore
  app-web/gatsby/onCreateNode.js
  app-web/gatsby/utils/githubRaw.js
  app-web/gatsby/utils/validators.js
  package-lock.json
Labels: task:pipeline

#1202 Minor proposal on line 62
  README.md
Labels: task:documentation

#1210 update workflow
  .github/workflows/devhub-markdown-test.yaml
Labels: task:pipeline

#1212 1193: (imp) Update logout button look and feel
  app-web/__tests__/components/__snapshots__/404.test.js.snap
  app-web/__tests__/components/__snapshots__/Navbar.test.js.snap
  app-web/__tests__/hoc/__snapshots__/LayoutComponent.test.js.snap
  app-web/__tests__/pages/__snapshots__/topics.test.js.snap
  app-web/src/components/Auth/Login/index.js
  app-web/src/components/Navbar/Navbar.js
Labels: task:ux/ui

#1213 Fixing journey map view
  app-web/src/components/Journey/SubwayLine.js
Labels: task:ux/ui

#1222 1220 (Improvement): Add 'list' toggle view to journeys
  app-web/.storybook/config.js
  app-web/.storybook/webpack.config.js
  app-web/__tests__/utils/helpers.test.js
  app-web/cypress/integration/Journeys/index.spec.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/GithubTemplate/Navigation/NavItem.js
  app-web/src/components/Journey/JourneyMap.js
  app-web/src/components/PrimaryFooter/PrimaryFooter.module.css
  app-web/src/components/TableOfContents/TableOfContents.js
  app-web/src/components/TopicPreview/TableofContents.js
  app-web/src/constants/ui.js
  app-web/src/hoc/Layout.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/journeys.js
  app-web/src/pages/topics.js
  app-web/src/utils/helpers.js
  app-web/stories/tableOfContents.stories.js
Labels: task:ux/ui

#1230 Algolia/1227 pipeline
  .jenkins/openshift/deploy-master.yaml
  .pipeline/lib/clone-algolia-index.js
  .pipeline/lib/delete-algolia-index.js
  .pipeline/lib/deploy.js
  .pipeline/utils/index.js
  Jenkinsfile
  app-web/__tests__/utils/algolia.test.js
  app-web/gatsby/onCreateNode.js
  app-web/src/config.js
  app-web/src/constants/api.js
  app-web/src/utils/algolia.js
  app-web/src/utils/hooks.js
  openshift/templates/dc.yaml
Labels: status:pending review, story:search

#1238 Add algolia brand to search bar
  .github/workflows/cypress.yml
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/cypress/integration/Home/search.spec.js
  app-web/cypress/screenshots/DynamicTopic/index.spec.js/Dynamic Topic Specs -- Arriving on the popular page -- can visit popular topics (failed).png
  app-web/cypress/screenshots/Home/search.spec.js/Searching from homepage -- can navigate to a card from a search (failed).png
  app-web/cypress/screenshots/Home/search.spec.js/Searching from homepage -- searches by a direct navigation (failed).png
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Page/CardsContainer.js
  app-web/src/components/UI/AlgoliaBrand/index.js
Labels: story:search

#1239 Additional e2e tests for algolia
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/cypress/integration/Home/search.spec.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Page/CardsContainer.js
Labels: story:search

#1243 Add remove service worker pluginn
  app-web/gatsby-config.js
  app-web/package-lock.json
  app-web/package.json
Labels: task:bug

#1236 Feat/algolia
  .github/workflows/cypress.yml
  .github/workflows/nodejs.yml
  .jenkins/openshift/deploy-master.yaml
  .jenkins/openshift/deploy-slave.yaml
  .pipeline/.env.example
  .pipeline/clone-algolia-index.js
  .pipeline/delete-algolia-index.js
  .pipeline/lib/clone-algolia-index.js
  .pipeline/lib/delete-algolia-index.js
  .pipeline/lib/deploy.js
  .pipeline/package-lock.json
  .pipeline/package.json
  .pipeline/utils/index.js
  Jenkinsfile
  app-web/.env.production.example
  app-web/__mocks__/algoliasearch/lite.js
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/pages/__snapshots__/Index.test.js.snap
  app-web/__tests__/pages/__snapshots__/resourceType.test.js.snap
  app-web/__tests__/pages/resourceType.test.js
  app-web/__tests__/utils/algolia.test.js
  app-web/__tests__/utils/hooks.test.js
  app-web/__tests__/utils/search.test.js
  app-web/cypress/integration/Home/search.spec.js
  app-web/cypress/screenshots/DynamicTopic/index.spec.js/Dynamic Topic Specs -- Arriving on the popular page -- can visit popular topics (failed).png
  app-web/gatsby-config.js
  app-web/gatsby-ssr.js
  app-web/gatsby/onCreateNode.js
  app-web/package-lock.json
  app-web/package.json
  app-web/src/components/Home/AlgoliaResults.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Page/CardsContainer.js
  app-web/src/components/UI/AlgoliaBrand/index.js
  app-web/src/config.js
  app-web/src/constants/api.js
  app-web/src/constants/search.js
  app-web/src/hoc/withResourceQuery.js
  app-web/src/pages/index.js
  app-web/src/templates/resourceType.js
  app-web/src/utils/algolia.js
  app-web/src/utils/hooks.js
  app-web/src/utils/search.js
  openshift/templates/algolia-build.secret.yaml
  openshift/templates/algolia-deployment.secret.yaml
  openshift/templates/bc.yaml
  openshift/templates/dc.yaml
Labels: story:search

#1246 Fix and issue where page refreshes ruin the CSS
  app-web/__tests__/components/__snapshots__/ResourcePreview.test.js.snap
  app-web/__tests__/pages/Index.test.js
  app-web/__tests__/utils/hooks.test.js
  app-web/cypress/integration/Home/search.spec.js
  app-web/gatsby/createPages.js
  app-web/gatsby/onCreateNode.js
  app-web/gatsby/onCreatePage.js
  app-web/src/AuthContext.js
  app-web/src/components/Card/CardsInColumns.js
  app-web/src/components/Home/Masthead.js
  app-web/src/components/Home/ResourcePreview.js
  app-web/src/components/Home/TopicsContainer.js
  app-web/src/components/Home/TopicsPreview.js
  app-web/src/components/Home/index.js
  app-web/src/components/Journey/JourneyMap.js
  app-web/src/components/PopularTopic/index.js
  app-web/src/components/Search/SearchGateResults.js
  app-web/src/components/Search/SearchResults.js
  app-web/src/components/Topic/index.js
  app-web/src/constants/strings.js
  app-web/src/pages/index.js
  app-web/src/pages/topics.js
  app-web/src/utils/hooks.js
Labels: task:bug
